#ifndef CONFIG_H_
#define CONFIG_H_

#ifdef __cplusplus
 extern "C" {
#endif

#include "stm32h7xx_hal.h"
#include <bsp.h>

typedef enum {
	ADC_RANK_UV_LIGHT_SENSOR = 1,
	ADC_RANK_NUMBERS,
}AdcRank;

extern uint32_t adc_buffer[];

/* MAJOR.MINOR.PATCH.BUILD
 * MAJOR version when you make incompatible API changes.
 * MINOR version when you add functionality in a backwards-compatible manner.
 * PATCH version when you make backwards-compatible bug fixes.
 * BUILD version during development (0 -> removed for the release)
 */
#define SOFTWARE_VERSION_MAJOR	1
#define SOFTWARE_VERSION_MINOR	0
#define SOFTWARE_VERSION_PATCH	0
#define SOFTWARE_VERSION_BUILD	23

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#if SOFTWARE_VERSION_BUILD == 0
#define VERSION_STRING "v" TOSTRING(SOFTWARE_VERSION_MAJOR) \
					   "." TOSTRING(SOFTWARE_VERSION_MINOR) \
					   "." TOSTRING(SOFTWARE_VERSION_PATCH)
#else
#define VERSION_STRING "v" TOSTRING(SOFTWARE_VERSION_MAJOR) \
					   "." TOSTRING(SOFTWARE_VERSION_MINOR) \
					   "." TOSTRING(SOFTWARE_VERSION_PATCH) \
					   "." TOSTRING(SOFTWARE_VERSION_BUILD)
#endif
/* Debug */
#define DEBUG_UART					USART1
#define DEBUG_UART_ENABLE_CLOCK		__HAL_RCC_USART1_CLK_ENABLE

#define DEBUG_TX_PIN_ENABLE_CLOCK	__HAL_RCC_GPIOA_CLK_ENABLE
#define DEBUG_TX_GPIO_PORT			GPIOA
#define DEBUG_TX_PIN				GPIO_PIN_9
#define DEBUG_TX_AF					GPIO_AF7_USART1
/* UV Light */
#define UV_LIGHT_1_PIN_ENABLE_CLOCK	__HAL_RCC_GPIOJ_CLK_ENABLE
#define UV_LIGHT_1_GPIO_PORT 		GPIOJ
#define UV_LIGHT_1_PIN 				GPIO_PIN_6

#define UV_LIGHT_2_PIN_ENABLE_CLOCK	__HAL_RCC_GPIOJ_CLK_ENABLE
#define UV_LIGHT_2_GPIO_PORT 		GPIOJ
#define UV_LIGHT_2_PIN 				GPIO_PIN_5

#define UV_LIGHT_SENSOR_ADC						ADC3
#define UV_LIGHT_SENSOR_ADC_CHANNEL				ADC_CHANNEL_6
#define UV_LIGHT_SENSOR_ADC_RANK				ADC_RANK_UV_LIGHT_SENSOR
#define UV_LIGHT_SENSOR_ADC_ENABLE_CLOCK		__HAL_RCC_ADC3_CLK_ENABLE
#define UV_LIGHT_SENSOR_ADC_PORT 				GPIOF
#define UV_LIGHT_SENSOR_ADC_PIN 				GPIO_PIN_10
#define UV_LIGHT_SENSOR_ADC_PIN_ENABLE_CLOCK	__HAL_RCC_GPIOF_CLK_ENABLE
#define UV_LIGHT_SENSOR_DMA_STREAM				DMA1_Stream1
//#define UV_LIGHT_SENSOR_DMA_CHANNEL				DMA_CHANNEL_1
#define UV_LIGHT_SENSOR_DMA_ENABLE_CLOCK		__HAL_RCC_DMA1_CLK_ENABLE
#define UV_LIGHT_SENSOR_DMA_STREAM_IRQN			DMA1_Stream1_IRQn
/* RGB LED */
#define RGB_LED_R_PIN_ENABLE_CLOCK	__HAL_RCC_GPIOJ_CLK_ENABLE
#define RGB_LED_R_GPIO_PORT 		GPIOJ
#define RGB_LED_R_PIN 				GPIO_PIN_8

#define RGB_LED_G_PIN_ENABLE_CLOCK	__HAL_RCC_GPIOJ_CLK_ENABLE
#define RGB_LED_G_GPIO_PORT 		GPIOJ
#define RGB_LED_G_PIN 				GPIO_PIN_10

#define RGB_LED_B_PIN_ENABLE_CLOCK	__HAL_RCC_GPIOK_CLK_ENABLE
#define RGB_LED_B_GPIO_PORT 		GPIOK
#define RGB_LED_B_PIN 				GPIO_PIN_0
/* Lid */
#define LID_SOLENOID_PIN_ENABLE_CLOCK	__HAL_RCC_GPIOJ_CLK_ENABLE
#define LID_SOLENOID_GPIO_PORT 			GPIOJ
#define LID_SOLENOID_PIN 				GPIO_PIN_4

#define LID_CLIP_SENSOR_PIN_ENABLE_CLOCK	__HAL_RCC_GPIOJ_CLK_ENABLE
#define LID_CLIP_SENSOR_GPIO_PORT 			GPIOJ
#define LID_CLIP_SENSOR_PIN 				GPIO_PIN_0

#define LID_HINGE_SENSOR_PIN_ENABLE_CLOCK	__HAL_RCC_GPIOJ_CLK_ENABLE
#define LID_HINGE_SENSOR_GPIO_PORT 			GPIOJ
#define LID_HINGE_SENSOR_PIN 				GPIO_PIN_7

/* Settings file */
static const char SETTINGS_INI_FILE[] = "SETTINGS.INI";

/* Endianness */
static const int BSTI = 1;  // Byte swap test integer
#define IS_BIG_ENDIAN() ((*(char*)&BSTI) == 0)

void swapBytes(void* object, size_t size);

#ifdef __cplusplus
}
#endif

#endif /* CONFIG_H_ */
