################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/bsp.c \
D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/hwjpeg_decode.c \
D:/Software/UvSmart/Utilities/JPEG/jpeg_utils.c \
D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/sd_diskio_dma.c \
D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/stm32h7xx_hal_timebase_tim.c \
D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/stm32h7xx_it.c \
D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/usbh_conf.c \
D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/usbh_diskio.c 

CPP_SRCS += \
D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/main.cpp 

OBJS += \
./Application/User/Core/bsp.o \
./Application/User/Core/hwjpeg_decode.o \
./Application/User/Core/jpeg_utils.o \
./Application/User/Core/main.o \
./Application/User/Core/sd_diskio_dma.o \
./Application/User/Core/stm32h7xx_hal_timebase_tim.o \
./Application/User/Core/stm32h7xx_it.o \
./Application/User/Core/usbh_conf.o \
./Application/User/Core/usbh_diskio.o 

C_DEPS += \
./Application/User/Core/bsp.d \
./Application/User/Core/hwjpeg_decode.d \
./Application/User/Core/jpeg_utils.d \
./Application/User/Core/sd_diskio_dma.d \
./Application/User/Core/stm32h7xx_hal_timebase_tim.d \
./Application/User/Core/stm32h7xx_it.d \
./Application/User/Core/usbh_conf.d \
./Application/User/Core/usbh_diskio.d 

CPP_DEPS += \
./Application/User/Core/main.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/Core/bsp.o: D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/bsp.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-d16 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DBSP_USE_CMSIS_OS -DCORE_CM7 '-DUSE_BPP=24' -DST -DUSE_FLOATING_POINT -DUSE_USB_HS -DUSE_PWR_LDO_SUPPLY__N -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/generated/images/include" -I../../../Gui/generated/fonts/include -I../../../Gui/generated/texts/include -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/gui/include" -I../../../Gui/gui/include/gui/audio_player_screen -I"D:/Software/UvSmart/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"D:/Software/UvSmart/Drivers/STM32H7xx_HAL_Driver/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Device/ST/STM32H7xx/Include" -I"D:/Software/UvSmart/Drivers/BSP/STM32H747I-Discovery" -I"D:/Software/UvSmart/Utilities/JPEG" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/include" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I../../../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../../../Middlewares/Third_Party/FatFs/src/drivers -I"D:/Software/UvSmart/Middlewares/Third_Party/LibJPEG/include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Config" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/target" -I"D:/Software/UvSmart/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Libraries" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/FatFS/src" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/MinIni"  -Os -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/hwjpeg_decode.o: D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/hwjpeg_decode.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-d16 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DBSP_USE_CMSIS_OS -DCORE_CM7 '-DUSE_BPP=24' -DST -DUSE_FLOATING_POINT -DUSE_USB_HS -DUSE_PWR_LDO_SUPPLY__N -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/generated/images/include" -I../../../Gui/generated/fonts/include -I../../../Gui/generated/texts/include -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/gui/include" -I../../../Gui/gui/include/gui/audio_player_screen -I"D:/Software/UvSmart/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"D:/Software/UvSmart/Drivers/STM32H7xx_HAL_Driver/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Device/ST/STM32H7xx/Include" -I"D:/Software/UvSmart/Drivers/BSP/STM32H747I-Discovery" -I"D:/Software/UvSmart/Utilities/JPEG" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/include" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I../../../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../../../Middlewares/Third_Party/FatFs/src/drivers -I"D:/Software/UvSmart/Middlewares/Third_Party/LibJPEG/include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Config" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/target" -I"D:/Software/UvSmart/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Libraries" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/FatFS/src" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/MinIni"  -Os -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/jpeg_utils.o: D:/Software/UvSmart/Utilities/JPEG/jpeg_utils.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-d16 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DBSP_USE_CMSIS_OS -DCORE_CM7 '-DUSE_BPP=24' -DST -DUSE_FLOATING_POINT -DUSE_USB_HS -DUSE_PWR_LDO_SUPPLY__N -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/generated/images/include" -I../../../Gui/generated/fonts/include -I../../../Gui/generated/texts/include -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/gui/include" -I../../../Gui/gui/include/gui/audio_player_screen -I"D:/Software/UvSmart/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"D:/Software/UvSmart/Drivers/STM32H7xx_HAL_Driver/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Device/ST/STM32H7xx/Include" -I"D:/Software/UvSmart/Drivers/BSP/STM32H747I-Discovery" -I"D:/Software/UvSmart/Utilities/JPEG" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/include" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I../../../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../../../Middlewares/Third_Party/FatFs/src/drivers -I"D:/Software/UvSmart/Middlewares/Third_Party/LibJPEG/include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Config" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/target" -I"D:/Software/UvSmart/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Libraries" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/FatFS/src" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/MinIni"  -Os -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/main.o: D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/main.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: MCU G++ Compiler'
	@echo $(PWD)
	arm-none-eabi-g++ -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-d16 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DBSP_USE_CMSIS_OS -DCORE_CM7 '-DUSE_BPP=24' -DST -DUSE_FLOATING_POINT -DUSE_USB_HS -DUSE_PWR_LDO_SUPPLY__N -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/generated/images/include" -I../../../Gui/generated/fonts/include -I../../../Gui/generated/texts/include -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/gui/include" -I../../../Gui/gui/include/gui/audio_player_screen -I"D:/Software/UvSmart/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"D:/Software/UvSmart/Drivers/STM32H7xx_HAL_Driver/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Device/ST/STM32H7xx/Include" -I"D:/Software/UvSmart/Drivers/BSP/STM32H747I-Discovery" -I"D:/Software/UvSmart/Utilities/JPEG" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/include" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I../../../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../../../Middlewares/Third_Party/FatFs/src/drivers -I"D:/Software/UvSmart/Middlewares/Third_Party/LibJPEG/include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Config" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/target" -I"D:/Software/UvSmart/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Libraries" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/FatFS/src" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/MinIni"  -Os -Wall -fmessage-length=0 -ffunction-sections -c -fno-exceptions -fno-rtti -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/sd_diskio_dma.o: D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/sd_diskio_dma.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-d16 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DBSP_USE_CMSIS_OS -DCORE_CM7 '-DUSE_BPP=24' -DST -DUSE_FLOATING_POINT -DUSE_USB_HS -DUSE_PWR_LDO_SUPPLY__N -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/generated/images/include" -I../../../Gui/generated/fonts/include -I../../../Gui/generated/texts/include -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/gui/include" -I../../../Gui/gui/include/gui/audio_player_screen -I"D:/Software/UvSmart/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"D:/Software/UvSmart/Drivers/STM32H7xx_HAL_Driver/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Device/ST/STM32H7xx/Include" -I"D:/Software/UvSmart/Drivers/BSP/STM32H747I-Discovery" -I"D:/Software/UvSmart/Utilities/JPEG" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/include" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I../../../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../../../Middlewares/Third_Party/FatFs/src/drivers -I"D:/Software/UvSmart/Middlewares/Third_Party/LibJPEG/include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Config" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/target" -I"D:/Software/UvSmart/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Libraries" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/FatFS/src" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/MinIni"  -Os -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/stm32h7xx_hal_timebase_tim.o: D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/stm32h7xx_hal_timebase_tim.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-d16 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DBSP_USE_CMSIS_OS -DCORE_CM7 '-DUSE_BPP=24' -DST -DUSE_FLOATING_POINT -DUSE_USB_HS -DUSE_PWR_LDO_SUPPLY__N -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/generated/images/include" -I../../../Gui/generated/fonts/include -I../../../Gui/generated/texts/include -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/gui/include" -I../../../Gui/gui/include/gui/audio_player_screen -I"D:/Software/UvSmart/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"D:/Software/UvSmart/Drivers/STM32H7xx_HAL_Driver/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Device/ST/STM32H7xx/Include" -I"D:/Software/UvSmart/Drivers/BSP/STM32H747I-Discovery" -I"D:/Software/UvSmart/Utilities/JPEG" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/include" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I../../../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../../../Middlewares/Third_Party/FatFs/src/drivers -I"D:/Software/UvSmart/Middlewares/Third_Party/LibJPEG/include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Config" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/target" -I"D:/Software/UvSmart/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Libraries" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/FatFS/src" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/MinIni"  -Os -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/stm32h7xx_it.o: D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/stm32h7xx_it.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-d16 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DBSP_USE_CMSIS_OS -DCORE_CM7 '-DUSE_BPP=24' -DST -DUSE_FLOATING_POINT -DUSE_USB_HS -DUSE_PWR_LDO_SUPPLY__N -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/generated/images/include" -I../../../Gui/generated/fonts/include -I../../../Gui/generated/texts/include -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/gui/include" -I../../../Gui/gui/include/gui/audio_player_screen -I"D:/Software/UvSmart/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"D:/Software/UvSmart/Drivers/STM32H7xx_HAL_Driver/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Device/ST/STM32H7xx/Include" -I"D:/Software/UvSmart/Drivers/BSP/STM32H747I-Discovery" -I"D:/Software/UvSmart/Utilities/JPEG" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/include" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I../../../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../../../Middlewares/Third_Party/FatFs/src/drivers -I"D:/Software/UvSmart/Middlewares/Third_Party/LibJPEG/include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Config" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/target" -I"D:/Software/UvSmart/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Libraries" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/FatFS/src" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/MinIni"  -Os -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/usbh_conf.o: D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/usbh_conf.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-d16 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DBSP_USE_CMSIS_OS -DCORE_CM7 '-DUSE_BPP=24' -DST -DUSE_FLOATING_POINT -DUSE_USB_HS -DUSE_PWR_LDO_SUPPLY__N -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/generated/images/include" -I../../../Gui/generated/fonts/include -I../../../Gui/generated/texts/include -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/gui/include" -I../../../Gui/gui/include/gui/audio_player_screen -I"D:/Software/UvSmart/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"D:/Software/UvSmart/Drivers/STM32H7xx_HAL_Driver/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Device/ST/STM32H7xx/Include" -I"D:/Software/UvSmart/Drivers/BSP/STM32H747I-Discovery" -I"D:/Software/UvSmart/Utilities/JPEG" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/include" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I../../../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../../../Middlewares/Third_Party/FatFs/src/drivers -I"D:/Software/UvSmart/Middlewares/Third_Party/LibJPEG/include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Config" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/target" -I"D:/Software/UvSmart/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Libraries" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/FatFS/src" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/MinIni"  -Os -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/usbh_diskio.o: D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Src/usbh_diskio.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-d16 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DBSP_USE_CMSIS_OS -DCORE_CM7 '-DUSE_BPP=24' -DST -DUSE_FLOATING_POINT -DUSE_USB_HS -DUSE_PWR_LDO_SUPPLY__N -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/generated/images/include" -I../../../Gui/generated/fonts/include -I../../../Gui/generated/texts/include -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/gui/include" -I../../../Gui/gui/include/gui/audio_player_screen -I"D:/Software/UvSmart/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"D:/Software/UvSmart/Drivers/STM32H7xx_HAL_Driver/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Device/ST/STM32H7xx/Include" -I"D:/Software/UvSmart/Drivers/BSP/STM32H747I-Discovery" -I"D:/Software/UvSmart/Utilities/JPEG" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"D:/Software/UvSmart/Middlewares/Third_Party/FreeRTOS/Source/include" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"D:/Software/UvSmart/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I../../../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../../../Middlewares/Third_Party/FatFs/src/drivers -I"D:/Software/UvSmart/Middlewares/Third_Party/LibJPEG/include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Config" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Core/Inc" -I"D:/Software/UvSmart/Drivers/CMSIS/Include" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/Gui/target" -I"D:/Software/UvSmart/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Libraries" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/FatFS/src" -I"D:/Software/UvSmart/Projects/STM32H747I-DISCO/Project/TouchGFX/SW4STM32/TouchGFX-STM32H747I-DISCO/Middleware/MinIni"  -Os -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


